"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()
from pathlib import Path
import sys
import os
from datetime import timedelta
from os import environ



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get("SECRET_KEY")  

# SECURITY WARNING: don't run with debug turned on in production!
# Control via environment variable: DEBUG=False for production, DEBUG=True for development
DEBUG = environ.get("DEBUG", "False") == "True"

 
CSRF_TRUSTED_ORIGINS = environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")

ALLOWED_HOSTS = environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 🔐 Two-Factor Authentication Apps
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',

    # 🔐 Security
    'axes',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_celery_beat',  # Celery Beat scheduler

    # Local apps
    'core.apps.CoreConfig',  # Core app with 2FA admin setup
    'user',
    'game',
    'challenge',
    'transaction',
    'notification',
    'social',
    'result',
    'access',
    'earning',
    'info',  # Admin Activity Logs
    'storages',
    'guide',
    'utils',
    'report',
    'tournament',
]

# Custom user model
AUTH_USER_MODEL = 'user.CustomUser'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  
        'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    }



# CORS settings
CORS_ALLOW_ALL_ORIGINS = False  # Only for development, configure properly in production
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # 🔐 2FA Middleware
    'axes.middleware.AxesMiddleware',  # 🔐 Rate limiting
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Enable project-level templates (e.g., templates/admin overrides)
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database configuration (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': environ.get('POSTGRES_DB'),
        'USER': environ.get('POSTGRES_USER'),
        'PASSWORD': environ.get('POSTGRES_PASSWORD'),
        'HOST': environ.get('POSTGRES_HOST'),
        'PORT': environ.get('POSTGRES_PORT', '5432'),
        'OPTIONS': {
            'sslmode': environ.get('POSTGRES_SSLMODE', 'disable'),
        },
    }
}

# Use SQLite for tests to avoid external DB dependency during testing
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'  # Set to Nepal timezone (UTC+05:45)

USE_I18N = True

USE_TZ = True

# Business logic timezone (explicit reference for code using local date boundaries)
BUSINESS_TIME_ZONE = TIME_ZONE


AUTH_USER_MODEL = 'user.CustomUser'


"""
Static & Media Files
--------------------
WhiteNoise is excellent for immutable static assets collected via collectstatic.
It should NOT be used to serve user-uploaded media files. Previously this file
configured WHITENOISE_ROOT / WHITENOISE_MEDIA_PREFIX which can interfere with
uploads (files appearing not to update after replacement, caching issues, or
permission mismatches inside containers). We remove that and rely on Django's
URL patterns (see core/urls.py) or the front-end web server (NGINX, etc.) to
serve MEDIA files. In Docker we mount a persistent volume at /app/media.
"""

# Static files (collected)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optional project-level static directory for additional assets / admin overrides
PROJECT_STATIC_DIR = os.path.join(BASE_DIR, 'static')
if os.path.isdir(PROJECT_STATIC_DIR):
    STATICFILES_DIRS = [PROJECT_STATIC_DIR]

# WhiteNoise for static (not media)
# For self-hosted: Use WhiteNoise with simple static files storage (no manifest requirement)
# Manifest requirement is more important for CDN deployments
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh only needed in dev

# Media (user uploads) - DigitalOcean Spaces Configuration
# ================================================================
# Integrated with DigitalOcean Spaces Object Storage for scalable,
# CDN-enabled media file serving with automatic backups and global delivery.
# ================================================================

# Check if DigitalOcean Spaces credentials are provided
USE_SPACES = bool(environ.get("DO_SPACES_KEY") and environ.get("DO_SPACES_SECRET"))

if USE_SPACES:
    # DigitalOcean Spaces configuration (S3-compatible)
    AWS_ACCESS_KEY_ID = environ.get("DO_SPACES_KEY")
    AWS_SECRET_ACCESS_KEY = environ.get("DO_SPACES_SECRET") 
    AWS_STORAGE_BUCKET_NAME = environ.get("DO_SPACES_BUCKET", "level-esport-matchmaking-bucket")
    AWS_S3_REGION_NAME = environ.get("DO_SPACES_REGION", "blr1")
    AWS_S3_ENDPOINT_URL = f"https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.cdn.digitaloceanspaces.com"
    
    
    # Storage backend configuration
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    
    # Django 4.2+ storage configuration
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    
    # Media files served via CDN
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    
    # File upload settings
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # 24 hours cache
    }
    AWS_DEFAULT_ACL = 'public-read'  # Make uploaded files publicly accessible
    AWS_S3_FILE_OVERWRITE = False    # Prevent accidental overwrites
    AWS_QUERYSTRING_AUTH = False     # No auth params in public URLs
    AWS_S3_VERIFY = True             # Verify SSL certificates
    
else:
    # Fallback to local media storage (development/testing)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect admin to admin homepage after login
LOGIN_REDIRECT_URL = '/admin/'
LOGIN_URL = '/admin/login/'



# ================================================================
# Celery Configuration with Valkey (Redis-compatible)
# ================================================================
# Valkey is a Redis fork that provides 100% compatibility with Redis APIs.
# DigitalOcean Managed Valkey service for production-grade message broker.
# ================================================================

# Construct Redis connection URL (internal Docker network, no SSL needed)
VALKEY_HOST = environ.get('VALKEY_HOST', 'localhost')
VALKEY_PORT = environ.get('VALKEY_PORT', '6379')
VALKEY_PASSWORD = environ.get('VALKEY_PASSWORD', '')

# Build the base URL for Redis
if VALKEY_PASSWORD:
    base_url = f"redis://:{VALKEY_PASSWORD}@{VALKEY_HOST}:{VALKEY_PORT}/0"
else:
    base_url = f"redis://{VALKEY_HOST}:{VALKEY_PORT}/0"

CELERY_BROKER_URL = base_url
CELERY_RESULT_BACKEND = base_url

# Celery Task Serialization Settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Task Execution Settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_TASK_ACKS_LATE = True  # Acknowledge task after execution
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue if worker crashes

# Worker Settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Number of tasks to prefetch per worker
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after N tasks (prevents memory leaks)

# Broker Connection Settings
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Result Backend Settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True

# ================================================================
# 🔐 Two-Factor Authentication Settings
# ================================================================
OTP_TOTP_ISSUER = 'Level Esports'  # Name shown in authenticator app
OTP_LOGIN_URL = '/admin/login/'
OTP_TOTP_SYNC = True
OTP_TOTP_TOLERANCE = 1  # Allow 1 time step before/after current time

# ================================================================
# 🔐 django-axes Rate Limiting Configuration
# ================================================================
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 hour
AXES_LOCKOUT_TEMPLATE = None
AXES_LOCKOUT_URL = None
AXES_ONLY_ADMIN_SITE = True
AXES_ENABLE_ADMIN = True
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_FORM_FIELD = 'username'
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_SENSITIVE_PARAMETERS = ['password', 'token']

# ================================================================
# Celery Beat Schedule for Periodic Tasks
# ================================================================
CELERY_BEAT_SCHEDULE = {
    'auto-magic-verification-every-2-5-minutes': {
        'task': 'result.auto_magic_verification',
        'schedule': 150.0,  # 150 seconds = 2.5 minutes
        'options': {
            'expires': 120.0,  # Task expires after 2 minutes if not executed
        }
    },
}

# ================================================================
# Logging Configuration
# ================================================================
# Enable detailed error logging even when DEBUG=False for production troubleshooting
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
